### ISSUE TITLE
When i click one of the audio settings, the sound suddenly becomes abnormally loud :( on my xz premium with android 10

### ISSUE THREAD

**Issue by ToniM93** [reiryuki/Sony-Xperia-10-Sound-Enhancement#1]
[logcat.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5749957/logcat.txt)
[prop.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5749958/prop.txt)

**Comment by reiryuki** [comment]
Send /vendor/etc/   audio_policy_configuration.xml and audio_output_policy.conf

**Comment by reiryuki** [comment]
Device codename?

ROM using?

**Comment by ToniM93** [comment]
codename: maple 
The rom is PixelExperience Plus

**Comment by ToniM93** [comment]
[audio_output_policy.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5749999/audio_output_policy.txt)

**Comment by ToniM93** [comment]
[audio_policy_configuration.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5750021/audio_policy_configuration.txt)

**Comment by reiryuki** [comment]
Firstly, try remove ACP if you using it

**Comment by ToniM93** [comment]
I don't have it but thanks anyway

**Comment by reiryuki** [comment]
Try add this line in /data/adb/modules/SoundEnhancement/system.prop:

vendor.audio.feature.deepbuffer_as_primary.enable=false


If still, try use ACP module

Try one by one,

**Comment by reiryuki** [comment]
Wait
It seems your device is not supported for pcm 24 bit, remove hires 24 bit module

**Comment by ToniM93** [comment]
Ok thanks I'll try

**Comment by reiryuki** [comment]
I will close this if no more issues

**Comment by ToniM93** [comment]
It's the same bro :(

**Comment by ToniM93** [comment]
only one audio mod works well and that is Dolby-Atmos-RC4-Ryuki-Mod

**Comment by ToniM93** [comment]
When I turn on something from the audio settings and the same thing.

**Comment by ToniM93** [comment]
only on DSEE-HX I have no problems

**Comment by reiryuki** [comment]
all audio effects files needed
system and vendor etc

**Comment by ToniM93** [comment]
[audio_policy_configuration.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5800541/audio_policy_configuration.txt)
[audio_effects.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5800548/audio_effects.txt)

**Comment by ToniM93** [comment]
other files needed?

**Comment by ToniM93** [comment]
[audio_effects.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5800570/audio_effects.txt)
this is from system\etc

**Comment by ToniM93** [comment]
[bluetooth_audio_policy_configuration.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5801561/bluetooth_audio_policy_configuration.txt)
[audio_policy_volumes.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5801562/audio_policy_volumes.txt)
[audio_policy_configuration_bluetooth_legacy_hal.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5801563/audio_policy_configuration_bluetooth_legacy_hal.txt)
[audio_platform_info.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5801564/audio_platform_info.txt)
[audio_io_policy.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5801565/audio_io_policy.txt)
[a2dp_in_audio_policy_configuration.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5801566/a2dp_in_audio_policy_configuration.txt)
[a2dp_audio_policy_configuration.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5801567/a2dp_audio_policy_configuration.txt)
[usb_audio_policy_configuration.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5801568/usb_audio_policy_configuration.txt)
[r_submix_audio_policy_configuration.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5801569/r_submix_audio_policy_configuration.txt)
[mixer_paths.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5801570/mixer_paths.txt)
[common_primary_audio_policy_configuration.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5801571/common_primary_audio_policy_configuration.txt)
[default_volume_tables.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5801572/default_volume_tables.txt)
[audio_tuning_mixer_tasha.txt](https://github.com/reiryuki/Sony-Xperia-10-Sound-Enhancement/files/5801575/audio_tuning_mixer_tasha.txt)

**Comment by ToniM93** [comment]
I think that is enough :)

**Comment by reiryuki** [comment]
sonyeffect is not loaded in ur audio_effect files

**Comment by ToniM93** [comment]
yes i know and what should i do?

**Comment by reiryuki** [comment]
Audio Modification Library module
See magisk repo

**Comment by ToniM93** [comment]
at the moment this one works for me without error Dolby-Atmos-RC4-Ryuki-Mod

**Comment by ToniM93** [comment]
I had tried but the same with Audio Modification Library module

**Comment by reiryuki** [comment]
U dont have audio_effects.xml ?
U only sent audio_effect.conf

**Comment by ToniM93** [comment]
they are in xml

**Comment by ToniM93** [comment]
I just put them in the post like that, otherwise there was no way

**Comment by ToniM93** [comment]
Thanks it working latest version with android 11 Arrow rom

**Comment by reiryuki** [comment]
Can you please send me:

su

ls -l /dev > /sdcard/dev.txt

without installing this module?

**Comment by Nitroil** [comment]
Hi,need help.When I turn on the effect, the volume becomes maximum and is not adjustable.Xiaomi Redmi not 11 pro 5g.Dolby atmos is already built into the system by the manufacturer. Stock firmware

**Comment by reiryuki** [comment]
@Nitroil I will never support 'talking only' without sending proper logs. If you want a fix, read #bug_report carefully, and send required files to the author.

**Comment by Nitroil** [comment]
what files do you want to dump?

**Comment by reiryuki** [comment]
@Nitroil do not spamming to another one thread
